name: Build and Version Bump

on:
  push:
    branches: ["main", "CICD-pipeline"]

permissions:
  contents: write  # REQUIRED for committing and pushing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # 3. Build the extension artifacts
      - name: Run build script
        run: python build.py

      # 4. Upload build artifacts
      - name: Upload Safari JS file
        uses: actions/upload-artifact@v4
        with:
          name: safari-extension
          path: dist/KURT_PRO_userscript.user.js

      - name: Upload Chrome extension zip
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: dist/KURT_PRO_chrome_extention.zip

      # 5. Auto bump version and push a tag (only run if this commit is not already a tag)
      - name: Bump version and create tag
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python bump.py
